spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: WHEN_MISSING
        timeout: 60
        max-retries: 1
      embedding:
        model: nomic-embed-text
      chat:
        options:
          model: llama3.2
          temperature: 0.7
#    vectorstore:
#      chroma:
#        client:
#          host: http://localhost
#          port: 8000
#        collection-name: springai_poc
#        initialize-schema: true
